### ISSUE TITLE
no pixel perfect

### ISSUE THREAD

**Issue by shevdi** [clicktronix/Indipixel#24]
Отличия от макета. Подогнать точнее. 
В файерфоксе верстка съезжает. Лучше, что бы отличий при просмотре между браузерами не было. Некоторые незначительные различия допускаются, но небольшие.
Это же относится и к резюме

**Comment by clicktronix** [comment]
а можно ссылочку на макет Indipixel? Потерял его где то

**Comment by shevdi** [comment]
C этим немного проблема. Я тоже не смог найти у себя сам файл. Просто у меня дома в самой программе PixelPerfect он еще висит. Могу разве что вечером сделать скриншот и выслать тебе.

**Comment by clicktronix** [comment]
Да не, не надо, спасибо) я Сергею напишу, думаю у него есть)
